#!/usr/bin/env node

/**
 * AI : Interactive setup script for Playwright authentication
 * Run with: node tests/setup-auth.js
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { createInterface } from 'readline';

const rl = createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setupAuth() {
  console.log('🎭 Playwright Authentication Setup for Construction Map\n');
  
  // AI : Check if .env.test.local already exists
  const envPath = '.env.test.local';
  
  if (existsSync(envPath)) {
    const overwrite = await question('⚠️  .env.test.local already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled. Edit .env.test.local manually if needed.');
      rl.close();
      return;
    }
  }
  
  console.log('Enter your Construction Map credentials for testing:\n');
  
  // AI : Get user credentials
  const email = await question('📧 Email: ');
  const password = await question('🔐 Password: ');
  
  const baseUrl = await question('🌐 Frontend URL (default: http://localhost:5173): ') || 'http://localhost:5173';
  const backendUrl = await question('⚙️  Backend URL (default: http://localhost:3000): ') || 'http://localhost:3000';
  
  // AI : Create .env.test.local content
  const envContent = `# AI : Local test credentials for Playwright
# Generated by setup-auth.js

TEST_USER_EMAIL=${email}
TEST_USER_PASSWORD=${password}

# Admin credentials (same as user for now)
TEST_ADMIN_EMAIL=${email}
TEST_ADMIN_PASSWORD=${password}

# URLs
TEST_BASE_URL=${baseUrl}
TEST_BACKEND_URL=${backendUrl}
`;

  // AI : Write the file
  writeFileSync(envPath, envContent);
  
  console.log('\n✅ Authentication setup complete!');
  console.log('\nNext steps:');
  console.log('1. Start your frontend: bun run dev-front');
  console.log('2. Run tests: bun run test:e2e');
  console.log('3. Or use UI mode: bun run test:e2e:ui');
  console.log('\n⚠️  Remember: .env.test.local is gitignored and contains your real credentials');
  
  rl.close();
}

setupAuth().catch(console.error);