/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOverlayDialog: typeof import('./src/components/dialogs/AddOverlayDialog.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    Button: typeof import('primevue/button')['default']
    CityMarkersToggle: typeof import('./src/components/map/CityMarkersToggle.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    ImageUploadDialog: typeof import('./src/components/dialogs/ImageUploadDialog.vue')['default']
    InfoPopup: typeof import('./src/components/map/InfoPopup.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MapView: typeof import('./src/components/map/MapView.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    OverlayEditor: typeof import('./src/components/map/OverlayEditor.vue')['default']
    OverlayItem: typeof import('./src/components/map/OverlayItem.vue')['default']
    ProjectActions: typeof import('./src/components/project/ProjectActions.vue')['default']
    ProjectEditor: typeof import('./src/components/project/ProjectEditor.vue')['default']
    ProjectForm: typeof import('./src/components/project/ProjectForm.vue')['default']
    ProjectHeader: typeof import('./src/components/project/ProjectHeader.vue')['default']
    ProjectList: typeof import('./src/components/project/ProjectList.vue')['default']
    ProjectOverlaysList: typeof import('./src/components/project/ProjectOverlaysList.vue')['default']
    ProjectOverlaysSection: typeof import('./src/components/project/ProjectOverlaysSection.vue')['default']
    ProjectPicker: typeof import('./src/components/project/ProjectPicker.vue')['default']
    ProjectViewer: typeof import('./src/components/project/ProjectViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TileLayerSelector: typeof import('./src/components/map/TileLayerSelector.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
