/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOverlayDialog: typeof import('./src/components/dialogs/AddOverlayDialog.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AuthModal: typeof import('./src/components/auth/AuthModal.vue')['default']
    Button: typeof import('primevue/button')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditModeToggle: typeof import('./src/components/map/EditModeToggle.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    ImageUploadDialog: typeof import('./src/components/dialogs/ImageUploadDialog.vue')['default']
    InfoPopup: typeof import('./src/components/map/InfoPopup.vue')['default']
    InfoPopupContainer: typeof import('./src/components/map/InfoPopupContainer.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LatestOverlaysPanel: typeof import('./src/components/layout/LatestOverlaysPanel.vue')['default']
    LayerControl: typeof import('./src/components/map/LayerControl.vue')['default']
    MapView: typeof import('./src/components/map/MapView.vue')['default']
    ModerationPanel: typeof import('./src/components/layout/ModerationPanel.vue')['default']
    MyContributionsPanel: typeof import('./src/components/layout/MyContributionsPanel.vue')['default']
    OverlayEditor: typeof import('./src/components/map/OverlayEditor.vue')['default']
    OverlayItem: typeof import('./src/components/map/OverlayItem.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Popover: typeof import('primevue/popover')['default']
    ProjectAccordionPanel: typeof import('./src/components/layout/ProjectAccordionPanel.vue')['default']
    ProjectDialog: typeof import('./src/components/project/ProjectDialog.vue')['default']
    ProjectEditor: typeof import('./src/components/project/ProjectEditor.vue')['default']
    ProjectForm: typeof import('./src/components/project/ProjectForm.vue')['default']
    ProjectPicker: typeof import('./src/components/project/ProjectPicker.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SideMenu: typeof import('./src/components/layout/SideMenu.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    UserMenu: typeof import('./src/components/auth/UserMenu.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
